In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(np.__version__)

[1 2 3 4]
2.3.2


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
a = np.array(34)
print(a.ndim)

0


In [9]:
b = np.array([1,2,3])
print(b.ndim)

1


In [10]:
c = np.array([[1,2],[3,4]])
print(c.ndim)

2


In [19]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d.ndim)

3


In [13]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [15]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [16]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [21]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==7)
print(x)

(array([], dtype=int64),)


In [22]:
arr = np.array([3,8,2,0])
print(np.sort(arr))

[0 2 3 8]


In [24]:
arr = np.array([43,67,87,90])
x = [True,False,True,False]
newarr = arr(x)
print(newarr)

TypeError: 'numpy.ndarray' object is not callable